name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [dashboard-app, api]

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install dependencies for each app
    - name: Install dependencies for ${{ matrix.app }}
      working-directory: ./apps/${{ matrix.app }}
      run: npm install

    # Run Prettier check for each app
    - name: Run Prettier for ${{ matrix.app }}
      working-directory: ./apps/${{ matrix.app }}
      run: npm run prettier:check

    # Run Lint for each app
    - name: Run Lint for ${{ matrix.app }}
      working-directory: ./apps/${{ matrix.app }}
      run: npm run lint

    # Run Tests for each app
    - name: Run Tests for ${{ matrix.app }}
      working-directory: ./apps/${{ matrix.app }}
      run: npm test
